"""Added skills and global restriction to user

Revision ID: 1d6d5b08dfed
Revises: d0c1c9c03f4f
Create Date: 2026-04-30 14:34:24.276156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6d5b08dfed'
down_revision = 'd0c1c9c03f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_executive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_restricted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_globally_restricted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_globally_restricted')
        batch_op.drop_column('skills')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('is_restricted')
        batch_op.drop_column('is_executive')

    # ### end Alembic commands ###
