"""Added LiveClass

Revision ID: 503585c4a678
Revises: f7035201a6cb
Create Date: 2026-03-26 13:30:56.013153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503585c4a678'
down_revision = 'f7035201a6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('room_name', sa.String(length=250), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_classes_room_name'), ['room_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_classes_room_name'))

    op.drop_table('live_classes')
    # ### end Alembic commands ###
