"""Add professional communication and interaction hub tables

Revision ID: d0c1c9c03f4f
Revises: fe10490595b6
Create Date: 2026-04-02 19:49:51.781190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c1c9c03f4f'
down_revision = 'fe10490595b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('original_staff_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hub_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['hub_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['support_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_whatsapp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_whatsapp')
        batch_op.drop_column('notify_email')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')

    op.drop_table('support_messages')
    op.drop_table('hub_comments')
    op.drop_table('support_threads')
    op.drop_table('hub_posts')
    # ### end Alembic commands ###
